# Comprehensive tool categories based on real hardware stores and industrial suppliers

TOOL_CATEGORIES = {
    "Hand Tools": {
        "subcategories": {
            "Hammers": [
                "Claw Hammers",
                "Ball Peen Hammers",
                "Sledge Hammers",
                "Framing Hammers",
                "Masonry Hammers",
                "Dead Blow Hammers",
                "Tack Hammers",
            ],
            "Screwdrivers": [
                "Phillips Screwdrivers",
                "Flathead Screwdrivers",
                "Torx Screwdrivers",
                "Robertson Screwdrivers",
                "Precision Screwdrivers",
                "Ratcheting Screwdrivers",
            ],
            "Wrenches": [
                "Combination Wrenches",
                "Open End Wrenches",
                "Box End Wrenches",
                "Adjustable Wrenches",
                "Pipe Wrenches",
                "Torque Wrenches",
                "Socket Wrenches",
            ],
            "Pliers": [
                "Needle Nose Pliers",
                "Lineman Pliers",
                "Diagonal Pliers",
                "Locking Pliers",
                "Wire Strippers",
                "Crimping Pliers",
                "Fencing Pliers",
            ],
            "Chisels": [
                "Wood Chisels",
                "Cold Chisels",
                "Masonry Chisels",
                "Mortise Chisels",
                "Turning Chisels",
                "Carving Chisels",
            ],
            "Hand Saws": [
                "Crosscut Saws",
                "Rip Saws",
                "Back Saws",
                "Coping Saws",
                "Hack Saws",
                "Dovetail Saws",
                "Pruning Saws",
            ],
            "Measuring Tools": [
                "Tape Measures",
                "Rulers",
                "Calipers",
                "Micrometers",
                "Squares",
                "Levels",
                "Protractors",
                "Gauges",
            ],
            "Files & Rasps": [
                "Flat Files",
                "Round Files",
                "Half Round Files",
                "Triangular Files",
                "Wood Rasps",
                "Metal Files",
                "Diamond Files",
            ],
            "Cutting Tools": [
                "Utility Knives",
                "Box Cutters",
                "Scoring Knives",
                "Craft Knives",
                "Snap-off Knives",
                "Retractable Knives",
            ],
        }
    },
    "Power Tools": {
        "subcategories": {
            "Drills": [
                "Cordless Drills",
                "Corded Drills",
                "Hammer Drills",
                "Impact Drills",
                "Right Angle Drills",
                "Drill Presses",
                "Magnetic Drills",
            ],
            "Saws": [
                "Circular Saws",
                "Miter Saws",
                "Table Saws",
                "Band Saws",
                "Jig Saws",
                "Reciprocating Saws",
                "Track Saws",
                "Tile Saws",
            ],
            "Sanders": [
                "Orbital Sanders",
                "Belt Sanders",
                "Palm Sanders",
                "Detail Sanders",
                "Disc Sanders",
                "Drum Sanders",
                "Random Orbital Sanders",
            ],
            "Grinders": [
                "Angle Grinders",
                "Bench Grinders",
                "Die Grinders",
                "Cut-off Tools",
                "Surface Grinders",
                "Tool Grinders",
            ],
            "Routers": [
                "Fixed Base Routers",
                "Plunge Routers",
                "Compact Routers",
                "CNC Routers",
                "Trim Routers",
                "Edge Routers",
            ],
            "Nailers": [
                "Framing Nailers",
                "Finish Nailers",
                "Brad Nailers",
                "Roofing Nailers",
                "Flooring Nailers",
                "Pin Nailers",
            ],
            "Impact Tools": [
                "Impact Drivers",
                "Impact Wrenches",
                "Impact Sockets",
                "Impact Bits",
                "Pneumatic Impact Tools",
            ],
            "Specialty Tools": [
                "Heat Guns",
                "Paint Sprayers",
                "Planers",
                "Joiners",
                "Biscuit Joiners",
                "Oscillating Tools",
            ],
        }
    },
    "Fasteners & Hardware": {
        "subcategories": {
            "Screws": [
                "Wood Screws",
                "Machine Screws",
                "Sheet Metal Screws",
                "Self-Tapping Screws",
                "Drywall Screws",
                "Deck Screws",
                "Security Screws",
            ],
            "Bolts & Nuts": [
                "Hex Bolts",
                "Carriage Bolts",
                "Machine Bolts",
                "Eye Bolts",
                "U-Bolts",
                "Hex Nuts",
                "Wing Nuts",
                "Lock Nuts",
            ],
            "Washers": [
                "Flat Washers",
                "Lock Washers",
                "Spring Washers",
                "Fender Washers",
                "Rubber Washers",
                "Nylon Washers",
            ],
            "Anchors": [
                "Concrete Anchors",
                "Drywall Anchors",
                "Hollow Wall Anchors",
                "Expansion Anchors",
                "Chemical Anchors",
                "Wedge Anchors",
            ],
            "Nails": [
                "Common Nails",
                "Finish Nails",
                "Brad Nails",
                "Roofing Nails",
                "Concrete Nails",
                "Masonry Nails",
                "Duplex Nails",
            ],
            "Hinges": [
                "Butt Hinges",
                "Piano Hinges",
                "Strap Hinges",
                "Spring Hinges",
                "Concealed Hinges",
                "Heavy Duty Hinges",
            ],
            "Brackets": [
                "Shelf Brackets",
                "Corner Brackets",
                "Angle Brackets",
                "Mounting Brackets",
                "Heavy Duty Brackets",
            ],
        }
    },
    "Safety Equipment": {
        "subcategories": {
            "Eye Protection": [
                "Safety Glasses",
                "Safety Goggles",
                "Face Shields",
                "Welding Helmets",
                "Prescription Safety Glasses",
            ],
            "Head Protection": [
                "Hard Hats",
                "Bump Caps",
                "Welding Helmets",
                "Face Shields",
                "Hair Nets",
            ],
            "Hand Protection": [
                "Work Gloves",
                "Cut Resistant Gloves",
                "Chemical Resistant Gloves",
                "Heat Resistant Gloves",
                "Disposable Gloves",
            ],
            "Hearing Protection": [
                "Ear Plugs",
                "Ear Muffs",
                "Electronic Hearing Protection",
                "Banded Ear Plugs",
            ],
            "Respiratory Protection": [
                "Dust Masks",
                "N95 Respirators",
                "Half Face Respirators",
                "Full Face Respirators",
                "Powered Air Respirators",
            ],
            "Body Protection": [
                "Safety Vests",
                "Coveralls",
                "Aprons",
                "Lab Coats",
                "High Visibility Clothing",
            ],
            "Fall Protection": [
                "Safety Harnesses",
                "Lanyards",
                "Self Retracting Lifelines",
                "Anchor Points",
                "Safety Nets",
            ],
            "First Aid": [
                "First Aid Kits",
                "Bandages",
                "Eye Wash Stations",
                "Emergency Showers",
                "AED Units",
            ],
        }
    },
    "Storage & Organization": {
        "subcategories": {
            "Tool Storage": [
                "Tool Boxes",
                "Tool Chests",
                "Tool Cabinets",
                "Rolling Tool Chests",
                "Portable Tool Boxes",
            ],
            "Tool Bags": [
                "Canvas Tool Bags",
                "Leather Tool Bags",
                "Electrician Bags",
                "Plumber Bags",
                "Carpenter Bags",
            ],
            "Wall Storage": [
                "Pegboards",
                "Tool Panels",
                "Slat Wall Systems",
                "Magnetic Tool Holders",
                "Wall Cabinets",
            ],
            "Shelving": [
                "Wire Shelving",
                "Steel Shelving",
                "Plastic Shelving",
                "Heavy Duty Shelving",
                "Mobile Shelving",
            ],
            "Storage Bins": [
                "Plastic Bins",
                "Metal Bins",
                "Stackable Bins",
                "Hanging Bins",
                "Clear Storage Bins",
            ],
            "Workbenches": [
                "Steel Workbenches",
                "Wood Workbenches",
                "Portable Workbenches",
                "Adjustable Workbenches",
            ],
            "Tool Belts": [
                "Leather Tool Belts",
                "Nylon Tool Belts",
                "Electrician Belts",
                "Carpenter Belts",
                "Suspenders",
            ],
        }
    },
    "Electrical": {
        "subcategories": {
            "Wiring": [
                "Electrical Wire",
                "Romex Cable",
                "Conduit Wire",
                "Coaxial Cable",
                "Speaker Wire",
                "Thermostat Wire",
            ],
            "Conduit": [
                "EMT Conduit",
                "PVC Conduit",
                "Flexible Conduit",
                "Rigid Conduit",
                "Liquid Tight Conduit",
            ],
            "Boxes & Enclosures": [
                "Junction Boxes",
                "Outlet Boxes",
                "Switch Boxes",
                "Panel Boxes",
                "Weather Proof Boxes",
            ],
            "Switches & Outlets": [
                "Light Switches",
                "Dimmer Switches",
                "GFCI Outlets",
                "USB Outlets",
                "Smart Switches",
            ],
            "Circuit Protection": [
                "Circuit Breakers",
                "Fuses",
                "GFCI Breakers",
                "Arc Fault Breakers",
                "Surge Protectors",
            ],
            "Connectors": [
                "Wire Nuts",
                "Terminal Blocks",
                "Splice Connectors",
                "Crimp Connectors",
                "Push-in Connectors",
            ],
            "Tools": [
                "Multimeters",
                "Wire Strippers",
                "Electrical Testers",
                "Fish Tapes",
                "Conduit Benders",
            ],
        }
    },
    "Plumbing": {
        "subcategories": {
            "Pipes": [
                "PVC Pipes",
                "Copper Pipes",
                "PEX Pipes",
                "Galvanized Pipes",
                "Cast Iron Pipes",
                "ABS Pipes",
            ],
            "Fittings": [
                "Elbows",
                "Tees",
                "Couplings",
                "Reducers",
                "Unions",
                "Caps",
                "Plugs",
            ],
            "Valves": [
                "Ball Valves",
                "Gate Valves",
                "Globe Valves",
                "Check Valves",
                "Pressure Relief Valves",
            ],
            "Fixtures": [
                "Faucets",
                "Toilets",
                "Sinks",
                "Shower Heads",
                "Bathtubs",
                "Water Heaters",
            ],
            "Drain Cleaning": [
                "Drain Snakes",
                "Plungers",
                "Drain Cleaners",
                "Hydro Jetters",
                "Drain Cameras",
            ],
            "Tools": [
                "Pipe Wrenches",
                "Basin Wrenches",
                "Pipe Cutters",
                "Tubing Cutters",
                "Soldering Tools",
            ],
            "Sealants": [
                "Pipe Thread Compound",
                "Plumber's Putty",
                "Silicone Sealant",
                "Pipe Dope",
                "Teflon Tape",
            ],
        }
    },
    "Garden & Outdoor": {
        "subcategories": {
            "Hand Tools": [
                "Shovels",
                "Rakes",
                "Hoes",
                "Trowels",
                "Pruning Shears",
                "Garden Forks",
                "Weeders",
            ],
            "Power Equipment": [
                "Lawn Mowers",
                "String Trimmers",
                "Leaf Blowers",
                "Hedge Trimmers",
                "Chain Saws",
                "Tillers",
            ],
            "Watering": [
                "Garden Hoses",
                "Sprinklers",
                "Drip Irrigation",
                "Watering Cans",
                "Nozzles",
                "Timers",
            ],
            "Chemicals": [
                "Fertilizers",
                "Herbicides",
                "Pesticides",
                "Fungicides",
                "Soil Amendments",
                "Mulch",
            ],
            "Containers": [
                "Planters",
                "Pots",
                "Hanging Baskets",
                "Window Boxes",
                "Raised Bed Kits",
            ],
            "Outdoor Power": [
                "Generators",
                "Pressure Washers",
                "Snow Blowers",
                "Wood Chippers",
                "Log Splitters",
            ],
        }
    },
    "Automotive": {
        "subcategories": {
            "Hand Tools": [
                "Socket Sets",
                "Wrench Sets",
                "Screwdriver Sets",
                "Pliers Sets",
                "Specialty Tools",
            ],
            "Power Tools": [
                "Impact Wrenches",
                "Air Compressors",
                "Grease Guns",
                "Battery Chargers",
                "Welders",
            ],
            "Diagnostic": [
                "Code Readers",
                "Multimeters",
                "Compression Testers",
                "Fuel Pressure Testers",
            ],
            "Fluids": [
                "Motor Oil",
                "Transmission Fluid",
                "Brake Fluid",
                "Coolant",
                "Power Steering Fluid",
            ],
            "Parts": [
                "Filters",
                "Spark Plugs",
                "Belts",
                "Hoses",
                "Gaskets",
                "Seals",
            ],
            "Equipment": [
                "Floor Jacks",
                "Jack Stands",
                "Creepers",
                "Work Lights",
                "Tool Carts",
            ],
        }
    },
    "HVAC": {
        "subcategories": {
            "Heating": [
                "Furnaces",
                "Boilers",
                "Heat Pumps",
                "Space Heaters",
                "Thermostats",
                "Ductwork",
            ],
            "Cooling": [
                "Air Conditioners",
                "Evaporative Coolers",
                "Fans",
                "Ventilation",
                "Refrigeration",
            ],
            "Tools": [
                "Manifold Gauges",
                "Refrigerant Recovery",
                "Leak Detectors",
                "Vacuum Pumps",
                "Torches",
            ],
            "Parts": [
                "Filters",
                "Belts",
                "Motors",
                "Compressors",
                "Coils",
                "Condensers",
            ],
            "Supplies": [
                "Refrigerants",
                "Cleaners",
                "Sealants",
                "Insulation",
                "Tape",
                "Fittings",
            ],
        }
    },
}

# Brand modifiers for creating realistic variations
BRAND_MODIFIERS = [
    "Professional",
    "Industrial",
    "Commercial",
    "Heavy Duty",
    "Precision",
    "Premium",
    "Economy",
    "Budget",
    "Standard",
    "Deluxe",
    "Pro Series",
    "Master",
    "Expert",
    "Contractor",
    "DIY",
    "Home",
    "Workshop",
    "Garage",
    "Portable",
    "Compact",
    "High Performance",
    "Super Duty",
    "Ultra",
    "Max",
    "Plus",
    "Advanced",
    "Classic",
]

# Size/Specification modifiers
SIZE_MODIFIERS = [
    "Mini",
    "Small",
    "Medium",
    "Large",
    "Extra Large",
    "Jumbo",
    "Giant",
    "1/4 inch",
    "3/8 inch",
    "1/2 inch",
    "3/4 inch",
    "1 inch",
    "2 inch",
    "6 inch",
    "8 inch",
    "10 inch",
    "12 inch",
    "14 inch",
    "16 inch",
    "Metric",
    "Standard",
    "SAE",
    "Torx",
    "Phillips",
    "Flathead",
]

# Material modifiers
MATERIAL_MODIFIERS = [
    "Steel",
    "Stainless Steel",
    "Carbon Steel",
    "Chrome",
    "Aluminum",
    "Brass",
    "Plastic",
    "Rubber",
    "Nylon",
    "Fiberglass",
    "Composite",
    "Titanium",
    "Cast Iron",
    "Forged",
    "Machined",
    "Hardened",
    "Tempered",
    "Coated",
]

# Application/Use case modifiers
APPLICATION_MODIFIERS = [
    "Automotive",
    "Marine",
    "Aerospace",
    "Construction",
    "Electrical",
    "Plumbing",
    "Woodworking",
    "Metalworking",
    "Welding",
    "HVAC",
    "Roofing",
    "Flooring",
    "Painting",
    "Landscaping",
    "Masonry",
    "Tile",
    "Concrete",
    "Drywall",
]

USER_ROLES = ["customer", "admin", "manager", "sales_rep", "warehouse_staff"]

REALISTIC_DOMAINS = [
    "gmail.com",
    "yahoo.com",
    "hotmail.com",
    "outlook.com",
    "aol.com",
    "icloud.com",
    "protonmail.com",
    "company.com",
    "business.net",
    "contractors.com",
    "tools.pro",
    "hardware.biz",
    "trades.org",
]
